import { createRequestHandler, type AppLoadContext, type ServerBuild } from '@remix-run/cloudflare';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

const handleRequest = createRequestHandler(serverBuild as unknown as ServerBuild, 'production');

/**
 * Cloudflare Workers entry point.
 *
 * This does what `functions/[[path]].ts` used to do for Pages: run the Remix
 * server build inside the Worker, while the client assets are served straight
 * from `./build/client` through the ASSETS binding in wrangler.toml.
 *
 * The load context matches the shape the app already expects from
 * `load-context.ts` (`env`, `cf`, `ctx`, `caches` - the app itself reads
 * `context.cloudflare.env`). The cast is only needed because wrangler's
 * `PlatformProxy` type describes its local development mock, which also exposes
 * a `default` cache that the Workers runtime does not have.
 */
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const cloudflare = {
      env,
      cf: request.cf,
      ctx,
      caches,
    } as unknown as AppLoadContext['cloudflare'];

    const response = await handleRequest(request, { cloudflare });

    if (response.status !== 404) {
      return response;
    }

    const assetResponse = await env.ASSETS.fetch(request);

    return assetResponse.status === 404 ? response : assetResponse;
  },
};
